development:
  adapter: sqlite3
  database: db/voting_platform_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/voting_platform_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/voting_platform_production.sqlite3
  pool: 5
  timeout: 5000 